// Generated by the Tensor Algebra CIRLowerer (tensor-compiler.org)
// taco "c(i)=a(i)*b(i)" -f=c:s:0 -f=a:s:0 -f=b:s:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c

int assemble(taco_tensor_t *c, taco_tensor_t *a, taco_tensor_t *b) {
  int* restrict c1_pos = (int*)(c->indices[0][0]);
  int* restrict c1_crd = (int*)(c->indices[0][1]);
  double* restrict c_vals = (double*)(c->vals);
  int* restrict a1_pos = (int*)(a->indices[0][0]);
  int* restrict a1_crd = (int*)(a->indices[0][1]);
  int* restrict b1_pos = (int*)(b->indices[0][0]);
  int* restrict b1_crd = (int*)(b->indices[0][1]);

  c1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  c1_pos[0] = 0;
  int32_t c1_crd_size = 1048576;
  c1_crd = (int32_t*)malloc(sizeof(int32_t) * c1_crd_size);
  int32_t ic = 0;


  int32_t ia = a1_pos[0];
  int32_t pa1_end = a1_pos[1];
  int32_t ib = b1_pos[0];
  int32_t pb1_end = b1_pos[1];

  while (ia < pa1_end && ib < pb1_end) {
    int32_t ia0 = a1_crd[ia];
    int32_t ib0 = b1_crd[ib];
    int32_t i = TACO_MIN(ia0,ib0);
    if (ia0 == i && ib0 == i) {
      if (c1_crd_size <= ic) {
        c1_crd = (int32_t*)realloc(c1_crd, sizeof(int32_t) * (c1_crd_size * 2));
        c1_crd_size *= 2;
      }
      c1_crd[ic] = i;
      ic++;
    }
    ia += (int32_t)(ia0 == i);
    ib += (int32_t)(ib0 == i);
  }

  c1_pos[1] = ic;

  c_vals = (double*)malloc(sizeof(double) * ic);

  c->indices[0][0] = (uint8_t*)(c1_pos);
  c->indices[0][1] = (uint8_t*)(c1_crd);
  c->vals = (uint8_t*)c_vals;
  return 0;
}
