// Generated by the Tensor Algebra CIRLowerer (tensor-compiler.org)
// taco "c(i)=a(i)*b(i)" -f=c:s:0 -f=a:s:0 -f=b:s:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <complex.h>
#include <string.h>
#if _OPENMP
#include <omp.h>
#endif
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#define TACO_DEREF(_a) (((___context___*)(*__ctx__))->_a)
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  uint8_t*     fill_value;    // tensor fill value
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
#if !_OPENMP
int omp_get_thread_num() { return 0; }
int omp_get_max_threads() { return 1; }
#endif
int cmp(const void *a, const void *b) {
  return *((const int*)a) - *((const int*)b);
}
int taco_gallop(int *array, int arrayStart, int arrayEnd, int target) {
  if (array[arrayStart] >= target || arrayStart >= arrayEnd) {
    return arrayStart;
  }
  int step = 1;
  int curr = arrayStart;
  while (curr + step < arrayEnd && array[curr + step] < target) {
    curr += step;
    step = step * 2;
  }

  step = step / 2;
  while (step > 0) {
    if (curr + step < arrayEnd && array[curr + step] < target) {
      curr += step;
    }
    step = step / 2;
  }
  return curr+1;
}
int taco_binarySearchAfter(int *array, int arrayStart, int arrayEnd, int target) {
  if (array[arrayStart] >= target) {
    return arrayStart;
  }
  int lowerBound = arrayStart; // always < target
  int upperBound = arrayEnd; // always >= target
  while (upperBound - lowerBound > 1) {
    int mid = (upperBound + lowerBound) / 2;
    int midValue = array[mid];
    if (midValue < target) {
      lowerBound = mid;
    }
    else if (midValue > target) {
      upperBound = mid;
    }
    else {
      return mid;
    }
  }
  return upperBound;
}
int taco_binarySearchBefore(int *array, int arrayStart, int arrayEnd, int target) {
  if (array[arrayEnd] <= target) {
    return arrayEnd;
  }
  int lowerBound = arrayStart; // always <= target
  int upperBound = arrayEnd; // always > target
  while (upperBound - lowerBound > 1) {
    int mid = (upperBound + lowerBound) / 2;
    int midValue = array[mid];
    if (midValue < target) {
      lowerBound = mid;
    }
    else if (midValue > target) {
      upperBound = mid;
    }
    else {
      return mid;
    }
  }
  return lowerBound;
}
taco_tensor_t* init_taco_tensor_t(int32_t order, int32_t csize,
                                  int32_t* dimensions, int32_t* mode_ordering,
                                  taco_mode_t* mode_types) {
  taco_tensor_t* t = (taco_tensor_t *) malloc(sizeof(taco_tensor_t));
  t->order         = order;
  t->dimensions    = (int32_t *) malloc(order * sizeof(int32_t));
  t->mode_ordering = (int32_t *) malloc(order * sizeof(int32_t));
  t->mode_types    = (taco_mode_t *) malloc(order * sizeof(taco_mode_t));
  t->indices       = (uint8_t ***) malloc(order * sizeof(uint8_t***));
  t->csize         = csize;
  for (int32_t i = 0; i < order; i++) {
    t->dimensions[i]    = dimensions[i];
    t->mode_ordering[i] = mode_ordering[i];
    t->mode_types[i]    = mode_types[i];
    switch (t->mode_types[i]) {
      case taco_mode_dense:
        t->indices[i] = (uint8_t **) malloc(1 * sizeof(uint8_t **));
        break;
      case taco_mode_sparse:
        t->indices[i] = (uint8_t **) malloc(2 * sizeof(uint8_t **));
        break;
    }
  }
  return t;
}
void deinit_taco_tensor_t(taco_tensor_t* t) {
  for (int i = 0; i < t->order; i++) {
    free(t->indices[i]);
  }
  free(t->indices);
  free(t->dimensions);
  free(t->mode_ordering);
  free(t->mode_types);
  free(t);
}
#endif

int compute(taco_tensor_t *c, taco_tensor_t *a, taco_tensor_t *b) {
  double* restrict c_vals = (double*)(c->vals);
  int* restrict a1_pos = (int*)(a->indices[0][0]);
  int* restrict a1_crd = (int*)(a->indices[0][1]);
  double* restrict a_vals = (double*)(a->vals);
  int* restrict b1_pos = (int*)(b->indices[0][0]);
  int* restrict b1_crd = (int*)(b->indices[0][1]);
  double* restrict b_vals = (double*)(b->vals);

  int32_t ic = 0;

  int32_t ia = a1_pos[0];
  int32_t pa1_end = a1_pos[1];
  int32_t ib = b1_pos[0];
  int32_t pb1_end = b1_pos[1];

  while (ia < pa1_end && ib < pb1_end) {
    int32_t ia0 = a1_crd[ia];
    int32_t ib0 = b1_crd[ib];
    int32_t i = TACO_MIN(ia0,ib0);
    if (ia0 == i && ib0 == i) {
      c_vals[ic] = a_vals[ia] * b_vals[ib];
      ic++;
    }
    ia += (int32_t)(ia0 == i);
    ib += (int32_t)(ib0 == i);
  }
  return 0;
}

int assemble(taco_tensor_t *c, taco_tensor_t *a, taco_tensor_t *b) {
  int* restrict c1_pos = (int*)(c->indices[0][0]);
  int* restrict c1_crd = (int*)(c->indices[0][1]);
  double* restrict c_vals = (double*)(c->vals);
  int* restrict a1_pos = (int*)(a->indices[0][0]);
  int* restrict a1_crd = (int*)(a->indices[0][1]);
  int* restrict b1_pos = (int*)(b->indices[0][0]);
  int* restrict b1_crd = (int*)(b->indices[0][1]);

  c1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  c1_pos[0] = 0;
  int32_t c1_crd_size = 1048576;
  c1_crd = (int32_t*)malloc(sizeof(int32_t) * c1_crd_size);
  int32_t ic = 0;


  int32_t ia = a1_pos[0];
  int32_t pa1_end = a1_pos[1];
  int32_t ib = b1_pos[0];
  int32_t pb1_end = b1_pos[1];

  while (ia < pa1_end && ib < pb1_end) {
    int32_t ia0 = a1_crd[ia];
    int32_t ib0 = b1_crd[ib];
    int32_t i = TACO_MIN(ia0,ib0);
    if (ia0 == i && ib0 == i) {
      if (c1_crd_size <= ic) {
        c1_crd = (int32_t*)realloc(c1_crd, sizeof(int32_t) * (c1_crd_size * 2));
        c1_crd_size *= 2;
      }
      c1_crd[ic] = i;
      ic++;
    }
    ia += (int32_t)(ia0 == i);
    ib += (int32_t)(ib0 == i);
  }

  c1_pos[1] = ic;

  c_vals = (double*)malloc(sizeof(double) * ic);

  c->indices[0][0] = (uint8_t*)(c1_pos);
  c->indices[0][1] = (uint8_t*)(c1_crd);
  c->vals = (uint8_t*)c_vals;
  return 0;
}

int evaluate(taco_tensor_t *c, taco_tensor_t *a, taco_tensor_t *b) {
  int* restrict c1_pos = (int*)(c->indices[0][0]);
  int* restrict c1_crd = (int*)(c->indices[0][1]);
  double* restrict c_vals = (double*)(c->vals);
  int* restrict a1_pos = (int*)(a->indices[0][0]);
  int* restrict a1_crd = (int*)(a->indices[0][1]);
  double* restrict a_vals = (double*)(a->vals);
  int* restrict b1_pos = (int*)(b->indices[0][0]);
  int* restrict b1_crd = (int*)(b->indices[0][1]);
  double* restrict b_vals = (double*)(b->vals);

  c1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  c1_pos[0] = 0;
  int32_t c1_crd_size = 1048576;
  c1_crd = (int32_t*)malloc(sizeof(int32_t) * c1_crd_size);
  int32_t ic = 0;
  int32_t c_capacity = 1048576;
  c_vals = (double*)malloc(sizeof(double) * c_capacity);


  int32_t ia = a1_pos[0];
  int32_t pa1_end = a1_pos[1];
  int32_t ib = b1_pos[0];
  int32_t pb1_end = b1_pos[1];

  while (ia < pa1_end && ib < pb1_end) {
    int32_t ia0 = a1_crd[ia];
    int32_t ib0 = b1_crd[ib];
    int32_t i = TACO_MIN(ia0,ib0);
    if (ia0 == i && ib0 == i) {
      if (c_capacity <= ic) {
        c_vals = (double*)realloc(c_vals, sizeof(double) * (c_capacity * 2));
        c_capacity *= 2;
      }
      c_vals[ic] = a_vals[ia] * b_vals[ib];
      if (c1_crd_size <= ic) {
        c1_crd = (int32_t*)realloc(c1_crd, sizeof(int32_t) * (c1_crd_size * 2));
        c1_crd_size *= 2;
      }
      c1_crd[ic] = i;
      ic++;
    }
    ia += (int32_t)(ia0 == i);
    ib += (int32_t)(ib0 == i);
  }

  c1_pos[1] = ic;

  c->indices[0][0] = (uint8_t*)(c1_pos);
  c->indices[0][1] = (uint8_t*)(c1_crd);
  c->vals = (uint8_t*)c_vals;
  return 0;
}

/*
 * The `pack` functions convert coordinate and value arrays in COO format,
 * with nonzeros sorted lexicographically by their coordinates, to the
 * specified input format.
 *
 * The `unpack` function converts the specified output format to coordinate
 * and value arrays in COO format.
 *
 * For both, the `_COO_pos` arrays contain two elements, where the first is 0
 * and the second is the number of nonzeros in the tensor.
 */

int pack_a(taco_tensor_t *a, int* a_COO1_pos, int* a_COO1_crd, double* a_COO_vals) {
  int* restrict a1_pos = (int*)(a->indices[0][0]);
  int* restrict a1_crd = (int*)(a->indices[0][1]);
  double* restrict a_vals = (double*)(a->vals);

  a1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  a1_pos[0] = 0;
  int32_t a1_crd_size = 1048576;
  a1_crd = (int32_t*)malloc(sizeof(int32_t) * a1_crd_size);
  int32_t ia = 0;
  int32_t a_capacity = 1048576;
  a_vals = (double*)malloc(sizeof(double) * a_capacity);


  int32_t ia_COO = a_COO1_pos[0];
  int32_t pa_COO1_end = a_COO1_pos[1];

  while (ia_COO < pa_COO1_end) {
    int32_t i = a_COO1_crd[ia_COO];
    double a_COO_val = a_COO_vals[ia_COO];
    ia_COO++;
    while (ia_COO < pa_COO1_end && a_COO1_crd[ia_COO] == i) {
      a_COO_val += a_COO_vals[ia_COO];
      ia_COO++;
    }
    if (a_capacity <= ia) {
      a_vals = (double*)realloc(a_vals, sizeof(double) * (a_capacity * 2));
      a_capacity *= 2;
    }
    a_vals[ia] = a_COO_val;
    if (a1_crd_size <= ia) {
      a1_crd = (int32_t*)realloc(a1_crd, sizeof(int32_t) * (a1_crd_size * 2));
      a1_crd_size *= 2;
    }
    a1_crd[ia] = i;
    ia++;
  }

  a1_pos[1] = ia;

  a->indices[0][0] = (uint8_t*)(a1_pos);
  a->indices[0][1] = (uint8_t*)(a1_crd);
  a->vals = (uint8_t*)a_vals;
  return 0;
}

int pack_b(taco_tensor_t *b, int* b_COO1_pos, int* b_COO1_crd, double* b_COO_vals) {
  int* restrict b1_pos = (int*)(b->indices[0][0]);
  int* restrict b1_crd = (int*)(b->indices[0][1]);
  double* restrict b_vals = (double*)(b->vals);

  b1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  b1_pos[0] = 0;
  int32_t b1_crd_size = 1048576;
  b1_crd = (int32_t*)malloc(sizeof(int32_t) * b1_crd_size);
  int32_t ib = 0;
  int32_t b_capacity = 1048576;
  b_vals = (double*)malloc(sizeof(double) * b_capacity);


  int32_t ib_COO = b_COO1_pos[0];
  int32_t pb_COO1_end = b_COO1_pos[1];

  while (ib_COO < pb_COO1_end) {
    int32_t i = b_COO1_crd[ib_COO];
    double b_COO_val = b_COO_vals[ib_COO];
    ib_COO++;
    while (ib_COO < pb_COO1_end && b_COO1_crd[ib_COO] == i) {
      b_COO_val += b_COO_vals[ib_COO];
      ib_COO++;
    }
    if (b_capacity <= ib) {
      b_vals = (double*)realloc(b_vals, sizeof(double) * (b_capacity * 2));
      b_capacity *= 2;
    }
    b_vals[ib] = b_COO_val;
    if (b1_crd_size <= ib) {
      b1_crd = (int32_t*)realloc(b1_crd, sizeof(int32_t) * (b1_crd_size * 2));
      b1_crd_size *= 2;
    }
    b1_crd[ib] = i;
    ib++;
  }

  b1_pos[1] = ib;

  b->indices[0][0] = (uint8_t*)(b1_pos);
  b->indices[0][1] = (uint8_t*)(b1_crd);
  b->vals = (uint8_t*)b_vals;
  return 0;
}

int unpack(int** c_COO1_pos_ptr, int** c_COO1_crd_ptr, double** c_COO_vals_ptr, taco_tensor_t *c) {
  int* c_COO1_pos;
  int* c_COO1_crd;
  double* c_COO_vals;
  int* restrict c1_pos = (int*)(c->indices[0][0]);
  int* restrict c1_crd = (int*)(c->indices[0][1]);
  double* restrict c_vals = (double*)(c->vals);

  c_COO1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  c_COO1_pos[0] = 0;
  int32_t c_COO1_crd_size = 1048576;
  c_COO1_crd = (int32_t*)malloc(sizeof(int32_t) * c_COO1_crd_size);
  int32_t ic_COO = 0;
  int32_t c_COO_capacity = 1048576;
  c_COO_vals = (double*)malloc(sizeof(double) * c_COO_capacity);


  for (int32_t ic = c1_pos[0]; ic < c1_pos[1]; ic++) {
    int32_t i = c1_crd[ic];
    if (c_COO_capacity <= ic_COO) {
      c_COO_vals = (double*)realloc(c_COO_vals, sizeof(double) * (c_COO_capacity * 2));
      c_COO_capacity *= 2;
    }
    c_COO_vals[ic_COO] = c_vals[ic];
    if (c_COO1_crd_size <= ic_COO) {
      c_COO1_crd = (int32_t*)realloc(c_COO1_crd, sizeof(int32_t) * (c_COO1_crd_size * 2));
      c_COO1_crd_size *= 2;
    }
    c_COO1_crd[ic_COO] = i;
    ic_COO++;
  }

  c_COO1_pos[1] = ic_COO;

  *c_COO1_pos_ptr = c_COO1_pos;
  *c_COO1_crd_ptr = c_COO1_crd;
  *c_COO_vals_ptr = c_COO_vals;
  return 0;
}
