name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev --ignore-pipfile
          pipenv run pip install torch==2.0.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html

      - name: Run tests
        working-directory: /home/runner/work/scorch/scorch
        run: |
          pipenv run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            pytest-report.xml
