name: pytest

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.1"

      - name: Install system dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ninja-build

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev --ignore-pipfile
          pipenv run pip install torch==2.0.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html

      - name: Run tests
        working-directory: /home/runner/work/scorch/scorch
        run: |
          pipenv run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            pytest-report.xml
